test develop-inst-noop: C:\Users\nrm19\Documents\repos\plover_spanish_mqd
test installed: appdirs==1.4.4,atomicwrites==1.4.0,attrs==21.2.0,colorama==0.4.4,iniconfig==1.1.1,packaging==21.0,plover==4.0.0.dev10,plover-python-dictionary==1.1.0,-e git+https://github.com/nvdaes/plover_spanish_mqd.git@255ffb729738014a267076a50fd1928afafbd286#egg=plover_spanish_mqd,plover-start-words==1.0.2,pluggy==1.0.0,py==1.10.0,pyparsing==2.4.7,pyserial==3.5,pytest==6.2.5,toml==0.10.2,wcwidth==0.2.5
test run-test-pre: PYTHONHASHSEED='917'
test run-test: commands[0] | pytest
============================= test session starts =============================
platform win32 -- Python 3.8.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
cachedir: .tox\test\.pytest_cache
rootdir: C:\Users\nrm19\Documents\repos\plover_spanish_mqd
collected 19 items

tests\test_blackbox.py FFF                                               [ 15%]
tests\test_double.py .                                                   [ 21%]
tests\test_initial.py .....                                              [ 47%]
tests\test_punctuation.py ....                                           [ 68%]
tests\test_single.py .                                                   [ 73%]
tests\test_user.py .....                                                 [100%]

================================== FAILURES ===================================
______________________ TestsBlackbox.test_regular_verb_1 ______________________

bb = <plover_build_utils.testing.blackbox.blackbox_test.<locals>.wrapper object at 0x0000022F31AE6760>
args = (), kwargs = {}

>   wrapper = lambda bb, *args, **kwargs: (blackbox_setup(bb), cls_or_fn(bb, *args, **kwargs), blackbox_replay(bb, name, test))
E   AssertionError: test_regular_verb_1
E     
E     "*": "=undo",
E     
E     Ccn	   ' camina'
E     PTVa-  ' caminaba'
E     *	   ' camina'
E     A*-	   ' caminá'
E     *	   ' camina'
E     E-	   ' camine'
E     *	   ' camina'
E   > Eneo-  ' caminen'
E     *	   ' camina'
E     O-	   ' camino'
E     
E      ' camine'
E   != ' caminen'

.tox\test\lib\site-packages\plover_build_utils\testing\blackbox.py:111: AssertionError
______________________ TestsBlackbox.test_regular_verb_2 ______________________

bb = <plover_build_utils.testing.blackbox.blackbox_test.<locals>.wrapper object at 0x0000022F31B23040>
args = (), kwargs = {}

>   wrapper = lambda bb, *args, **kwargs: (blackbox_setup(bb), cls_or_fn(bb, *args, **kwargs), blackbox_replay(bb, name, test))
E   AssertionError: test_regular_verb_2
E     
E     "*": "=undo",
E     
E     PCVRcs	 ' llega'
E   > PTVAneo	 ' llegaban'
E     *		 ' llega'
E     Eneo	 ' lleguen'
E     *		 ' llega'
E     E*		 ' llegué'
E     
E      ' llegaba'
E   != ' llegaban'

.tox\test\lib\site-packages\plover_build_utils\testing\blackbox.py:111: AssertionError
_______________________ TestsBlackbox.test_irregular_1 ________________________

bb = <plover_build_utils.testing.blackbox.blackbox_test.<locals>.wrapper object at 0x0000022F31C03E20>
args = (), kwargs = {}

>   wrapper = lambda bb, *args, **kwargs: (blackbox_setup(bb), cls_or_fn(bb, *args, **kwargs), blackbox_replay(bb, name, test))
E   AssertionError: test_irregular_1
E     
E     "*": "=undo",
E     
E     PCTcs  ' juga'
E     TNo	   ' jugado'
E     *	   ' juga'
E   > Eneo   ' jueguen'
E     *	   ' juga'
E     E*	   ' jugué'
E     	  *		 ' juga'
E     Astpo  ' jugando'
E     
E      ' jugue'
E   != ' jueguen'

.tox\test\lib\site-packages\plover_build_utils\testing\blackbox.py:111: AssertionError
=========================== short test summary info ===========================
FAILED tests/test_blackbox.py::TestsBlackbox::test_regular_verb_1 - Assertion...
FAILED tests/test_blackbox.py::TestsBlackbox::test_regular_verb_2 - Assertion...
FAILED tests/test_blackbox.py::TestsBlackbox::test_irregular_1 - AssertionErr...
======================== 3 failed, 16 passed in 1.01s =========================
ERROR: InvocationError for command 'C:\Users\nrm19\Documents\repos\plover_spanish_mqd\.tox\test\Scripts\pytest.EXE' (exited with code 1)
___________________________________ summary ___________________________________
ERROR:   test: commands failed
